[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-floof.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # allows it automatically make a bootable image with `cargo run`
